/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject;

import java.sql.Connection;
import javax.swing.JLayeredPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author miguelfreitas
 */
public class DB extends javax.swing.JFrame {

    /**
     * Creates new form DB
     */
    public DB() {
  
        initComponents();
        jPSTurma.setEnabled(false);
        jPSTurma.setVisible(false);
        
        jPSAula.setEnabled(false);
        jPSAula.setVisible(false);
        
        jPCAula.setEnabled(false);
        jPCAula.setVisible(false);
        
        jPDAula.setEnabled(false);
        jPDAula.setVisible(false);
        
        jPCMat.setEnabled(false);
        jPCMat.setVisible(false);
        
        jPDUser.setEnabled(false);
        jPDUser.setVisible(false);
        
        jPCUser.setEnabled(false);
        jPCUser.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCMat = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        NMat = new javax.swing.JTextField();
        MInsert = new javax.swing.JButton();
        jPCAula = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        CAname_mat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CACPF_Prof = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CAPreço = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Local = new javax.swing.JTextField();
        CACriar = new javax.swing.JButton();
        Dia = new javax.swing.JComboBox<>();
        Mes = new javax.swing.JComboBox<>();
        Hora = new javax.swing.JComboBox<>();
        Minuto = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        ano = new javax.swing.JComboBox<>();
        jPDAula = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        DAID = new javax.swing.JTextField();
        DADelete = new javax.swing.JButton();
        jPDUser = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DCPF = new javax.swing.JTextField();
        DUDelete = new javax.swing.JButton();
        jPCUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CPF = new javax.swing.JTextField();
        UNome = new javax.swing.JTextField();
        Cel = new javax.swing.JTextField();
        Sexo = new javax.swing.JComboBox<>();
        email = new javax.swing.JTextField();
        Passwd = new javax.swing.JPasswordField();
        UInserir = new javax.swing.JButton();
        jPSTurma = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SAula = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        SAID = new javax.swing.JTextField();
        STListar = new javax.swing.JButton();
        jPSAula = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        STAula = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        JSAmat = new javax.swing.JTextField();
        jSAListar = new javax.swing.JButton();
        TurmaIn = new javax.swing.JButton();
        TinCPF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        JMenu = new javax.swing.JMenuBar();
        Insert = new javax.swing.JMenu();
        CUser = new javax.swing.JMenuItem();
        CMat = new javax.swing.JMenuItem();
        CClass = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenu();
        DUser = new javax.swing.JMenuItem();
        DClass = new javax.swing.JMenuItem();
        Select = new javax.swing.JMenu();
        STurma = new javax.swing.JMenuItem();
        SClass = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BDProject");

        jLabel7.setText("Nome");

        MInsert.setText("Inserir");
        MInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MInsertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCMatLayout = new javax.swing.GroupLayout(jPCMat);
        jPCMat.setLayout(jPCMatLayout);
        jPCMatLayout.setHorizontalGroup(
            jPCMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCMatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCMatLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 491, Short.MAX_VALUE))
                    .addComponent(NMat))
                .addContainerGap())
            .addGroup(jPCMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPCMatLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MInsert)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPCMatLayout.setVerticalGroup(
            jPCMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCMatLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(NMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(jPCMatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPCMatLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MInsert)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel8.setText("Nome Materia");

        jLabel9.setText("CPF_Prof");

        jLabel10.setText("Horário");

        jLabel11.setText("Preço");

        jLabel12.setText("Local");

        CACriar.setText("Criar");
        CACriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CACriarActionPerformed(evt);
            }
        });

        Dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        Hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));

        Minuto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55", " " }));

        jLabel18.setText(":");

        ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", " " }));

        javax.swing.GroupLayout jPCAulaLayout = new javax.swing.GroupLayout(jPCAula);
        jPCAula.setLayout(jPCAulaLayout);
        jPCAulaLayout.setHorizontalGroup(
            jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCAulaLayout.createSequentialGroup()
                .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCAulaLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(CACriar))
                    .addGroup(jPCAulaLayout.createSequentialGroup()
                        .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCAulaLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCAulaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CAname_mat)
                            .addComponent(CACPF_Prof)
                            .addComponent(CAPreço)
                            .addComponent(Local, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPCAulaLayout.createSequentialGroup()
                                .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPCAulaLayout.setVerticalGroup(
            jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCAulaLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CAname_mat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(CACPF_Prof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Minuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(CAPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(CACriar)
                .addGap(57, 57, 57))
        );

        jLabel14.setText("ID_AULA");

        DADelete.setText("Excluir");
        DADelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DADeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDAulaLayout = new javax.swing.GroupLayout(jPDAula);
        jPDAula.setLayout(jPDAulaLayout);
        jPDAulaLayout.setHorizontalGroup(
            jPDAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDAulaLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPDAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPDAulaLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(DADelete))
                    .addComponent(jLabel14)
                    .addComponent(DAID, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        jPDAulaLayout.setVerticalGroup(
            jPDAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDAulaLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(DAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(DADelete)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jLabel13.setText("CPF");

        DUDelete.setText("Excluir");
        DUDelete.setToolTipText("");
        DUDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DUDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPDUserLayout = new javax.swing.GroupLayout(jPDUser);
        jPDUser.setLayout(jPDUserLayout);
        jPDUserLayout.setHorizontalGroup(
            jPDUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPDUserLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPDUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(DCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(jPDUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPDUserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DUDelete)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPDUserLayout.setVerticalGroup(
            jPDUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPDUserLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(DCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
            .addGroup(jPDUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPDUserLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DUDelete)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel1.setText("CPF");

        jLabel2.setText("Nome");

        jLabel3.setText("Sexo");

        jLabel4.setText("Cel");

        jLabel5.setText("email");

        jLabel6.setText("Senha");

        Sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        Passwd.setText("senha");

        UInserir.setText("Inserir");
        UInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCUserLayout = new javax.swing.GroupLayout(jPCUser);
        jPCUser.setLayout(jPCUserLayout);
        jPCUserLayout.setHorizontalGroup(
            jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCUserLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCUserLayout.createSequentialGroup()
                        .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CPF)
                            .addComponent(UNome)
                            .addComponent(Cel)
                            .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email)
                            .addComponent(Passwd, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPCUserLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(UInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        jPCUserLayout.setVerticalGroup(
            jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCUserLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(UNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Cel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Passwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(UInserir)
                .addGap(41, 41, 41))
        );

        SAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cel", "Email"
            }
        ));
        jScrollPane1.setViewportView(SAula);

        jLabel15.setText("ID_Aula");

        STListar.setText("Listar");
        STListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPSTurmaLayout = new javax.swing.GroupLayout(jPSTurma);
        jPSTurma.setLayout(jPSTurmaLayout);
        jPSTurmaLayout.setHorizontalGroup(
            jPSTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSTurmaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPSTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addGroup(jPSTurmaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SAID, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPSTurmaLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(STListar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPSTurmaLayout.setVerticalGroup(
            jPSTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSTurmaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPSTurmaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(SAID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(STListar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        STAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Materia", "Nome Prof", "Cel Prof", "Preço", "Local"
            }
        ));
        jScrollPane2.setViewportView(STAula);

        jLabel16.setText("Materia Desejada");

        jSAListar.setText("Listar");
        jSAListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSAListarActionPerformed(evt);
            }
        });

        TurmaIn.setText("Entrar na Turma");
        TurmaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurmaInActionPerformed(evt);
            }
        });

        jLabel17.setText("CPF");

        javax.swing.GroupLayout jPSAulaLayout = new javax.swing.GroupLayout(jPSAula);
        jPSAula.setLayout(jPSAulaLayout);
        jPSAulaLayout.setHorizontalGroup(
            jPSAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPSAulaLayout.createSequentialGroup()
                .addGroup(jPSAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPSAulaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JSAmat, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPSAulaLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jSAListar)))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPSAulaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(15, 15, 15)
                .addComponent(TinCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TurmaIn)
                .addGap(76, 76, 76))
        );
        jPSAulaLayout.setVerticalGroup(
            jPSAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPSAulaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPSAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(JSAmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSAListar)
                .addGap(18, 18, 18)
                .addGroup(jPSAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TurmaIn)
                    .addComponent(TinCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        Insert.setText("Cadastrar");

        CUser.setText("Usuário");
        CUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUserActionPerformed(evt);
            }
        });
        Insert.add(CUser);

        CMat.setText("Matéria");
        CMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMatActionPerformed(evt);
            }
        });
        Insert.add(CMat);

        CClass.setText("Aula");
        CClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CClassActionPerformed(evt);
            }
        });
        Insert.add(CClass);

        JMenu.add(Insert);

        Delete.setText("Excluir");

        DUser.setText("Usuário");
        DUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DUserActionPerformed(evt);
            }
        });
        Delete.add(DUser);

        DClass.setText("Aula");
        DClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DClassActionPerformed(evt);
            }
        });
        Delete.add(DClass);

        JMenu.add(Delete);

        Select.setText("Consultar");

        STurma.setText("Turma");
        STurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STurmaActionPerformed(evt);
            }
        });
        Select.add(STurma);

        SClass.setText("Aula");
        SClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SClassActionPerformed(evt);
            }
        });
        Select.add(SClass);

        JMenu.add(Select);

        setJMenuBar(JMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPCUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPCMat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPCAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPDUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPDAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPSTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPSAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPCUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPCMat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPCAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPDUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPDAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPSTurma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPSAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUserActionPerformed
        // TODO add your handling code here:
        jPSTurma.setEnabled(false);
        jPSTurma.setVisible(false);
        
        jPSAula.setEnabled(false);
        jPSAula.setVisible(false);
        
        jPCAula.setEnabled(false);
        jPCAula.setVisible(false);
        
        jPDAula.setEnabled(false);
        jPDAula.setVisible(false);
        
        jPCMat.setEnabled(false);
        jPCMat.setVisible(false);
        
        jPDUser.setEnabled(false);
        jPDUser.setVisible(false);
        
        jPCUser.setEnabled(true);
        jPCUser.setVisible(true);
        
        
    }//GEN-LAST:event_CUserActionPerformed

    private void CMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMatActionPerformed
        // TODO add your handling code here:
        jPSTurma.setEnabled(false);
        jPSTurma.setVisible(false);
        
        jPSAula.setEnabled(false);
        jPSAula.setVisible(false);
        
        jPCAula.setEnabled(false);
        jPCAula.setVisible(false);
        
        jPDAula.setEnabled(false);
        jPDAula.setVisible(false);
        
        jPCMat.setEnabled(true);
        jPCMat.setVisible(true);
        
        jPDUser.setEnabled(false);
        jPDUser.setVisible(false);
        
        jPCUser.setEnabled(false);
        jPCUser.setVisible(false);
    }//GEN-LAST:event_CMatActionPerformed

    private void CClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CClassActionPerformed
        // TODO add your handling code here:
        jPSTurma.setEnabled(false);
        jPSTurma.setVisible(false);
        
        jPSAula.setEnabled(false);
        jPSAula.setVisible(false);
        
        jPCAula.setEnabled(true);
        jPCAula.setVisible(true);
        
        jPDAula.setEnabled(false);
        jPDAula.setVisible(false);
        
        jPCMat.setEnabled(false);
        jPCMat.setVisible(false);
        
        jPDUser.setEnabled(false);
        jPDUser.setVisible(false);
        
        jPCUser.setEnabled(false);
        jPCUser.setVisible(false);
    }//GEN-LAST:event_CClassActionPerformed

    private void DUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DUserActionPerformed
        // TODO add your handling code here:
        jPSTurma.setEnabled(false);
        jPSTurma.setVisible(false);
        
        jPSAula.setEnabled(false);
        jPSAula.setVisible(false);
        
        jPCAula.setEnabled(false);
        jPCAula.setVisible(false);
        
        jPDAula.setEnabled(false);
        jPDAula.setVisible(false);
        
        jPCMat.setEnabled(false);
        jPCMat.setVisible(false);
        
        jPDUser.setEnabled(true);
        jPDUser.setVisible(true);
        
        jPCUser.setEnabled(false);
        jPCUser.setVisible(false);
    }//GEN-LAST:event_DUserActionPerformed

    private void DClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DClassActionPerformed
        // TODO add your handling code here:
        jPSTurma.setEnabled(false);
        jPSTurma.setVisible(false);
        
        jPSAula.setEnabled(false);
        jPSAula.setVisible(false);
        
        jPCAula.setEnabled(false);
        jPCAula.setVisible(false);
        
        jPDAula.setEnabled(true);
        jPDAula.setVisible(true);
        
        jPCMat.setEnabled(false);
        jPCMat.setVisible(false);
        
        jPDUser.setEnabled(false);
        jPDUser.setVisible(false);
        
        jPCUser.setEnabled(false);
        jPCUser.setVisible(false);
    }//GEN-LAST:event_DClassActionPerformed

    private void STurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STurmaActionPerformed
        // TODO add your handling code here:
        jPSTurma.setEnabled(true);
        jPSTurma.setVisible(true);
        
        jPSAula.setEnabled(false);
        jPSAula.setVisible(false);
        
        jPCAula.setEnabled(false);
        jPCAula.setVisible(false);
        
        jPDAula.setEnabled(false);
        jPDAula.setVisible(false);
        
        jPCMat.setEnabled(false);
        jPCMat.setVisible(false);
        
        jPDUser.setEnabled(false);
        jPDUser.setVisible(false);
        
        jPCUser.setEnabled(false);
        jPCUser.setVisible(false);
    }//GEN-LAST:event_STurmaActionPerformed

    private void SClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SClassActionPerformed
        // TODO add your handling code here:
        jPSTurma.setEnabled(false);
        jPSTurma.setVisible(false);
        
        jPSAula.setEnabled(true);
        jPSAula.setVisible(true);
        
        jPCAula.setEnabled(false);
        jPCAula.setVisible(false);
        
        jPDAula.setEnabled(false);
        jPDAula.setVisible(false);
        
        jPCMat.setEnabled(false);
        jPCMat.setVisible(false);
        
        jPDUser.setEnabled(false);
        jPDUser.setVisible(false);
        
        jPCUser.setEnabled(false);
        jPCUser.setVisible(false);
    }//GEN-LAST:event_SClassActionPerformed

    private void UInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UInserirActionPerformed
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "INSERT INTO pessoa (cpf, nome, sexo, cel, email, senha) VALUES ("
                    + CPF.getText() + ", '" + UNome.getText()+ "', '" + Sexo.getSelectedItem() + "', "
                    + Cel.getText() + ", '" + email.getText() + "', '" + Passwd.getText() +"');";
        try {
            stm = con.createStatement();
            stm.executeUpdate(query);
            con.close();
            JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        CPF.setText("");
        UNome.setText("");
        Cel.setText("");
        email.setText("");
        Passwd.setText("senha");
            
    }//GEN-LAST:event_UInserirActionPerformed

    private void MInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MInsertActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "INSERT INTO materia (nome) VALUES ('"
                    +NMat.getText() +"');";
        try {
            stm = con.createStatement();
            stm.executeUpdate(query);
            con.close();
            JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        NMat.setText("");
    }//GEN-LAST:event_MInsertActionPerformed

    private void CACriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CACriarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "INSERT INTO aula (materiaid, cpf_prof, time, preço, local) VALUES ("
                    + "(SELECT id FROM materia WHERE nome = '" + CAname_mat.getText() + "' LIMIT 1), " + CACPF_Prof.getText()+ ", "
                    + "TIMESTAMP '" + ano.getSelectedItem() + "/" + Mes.getSelectedItem() + "/" + Dia.getSelectedItem()
                    + " " + Hora.getSelectedItem() +":" + Minuto.getSelectedItem() + ":00', "
                    + CAPreço.getText() + ", (SELECT id from local WHERE nome = '" + Local.getText() + "'));";
        try {
            stm = con.createStatement();
            stm.executeUpdate(query);
            con.close();
            JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso");        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        CAname_mat.setText("");
        CACPF_Prof.setText("");
        CAPreço.setText("");
        Local.setText("");
    }//GEN-LAST:event_CACriarActionPerformed

    private void DADeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DADeleteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "DELETE FROM aula WHERE id = " + DAID.getText();
        try {
            stm = con.createStatement();
            stm.executeUpdate(query);
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_DADeleteActionPerformed

    private void DUDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DUDeleteActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "DELETE FROM pessoa WHERE cpf = " + DCPF.getText();
        try {
            stm = con.createStatement();
            stm.executeUpdate(query);
            con.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_DUDeleteActionPerformed

    private void STListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STListarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }
        DefaultTableModel model = (DefaultTableModel) SAula.getModel();
        int n = 0;
        while(n < model.getRowCount()){
            model.removeRow(n);
        }
        try {
            query = "SELECT a.nome, a.cel, a.email from pessoa as a, "
                    + "turma as b, aula as c WHERE c.id = " + SAID.getText() + " and c.id = b.id_aula;";
            stm = con.createStatement();
            rs = stm.executeQuery(query);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("nome"),rs.getString("cel"),
                    rs.getString("email")});
        }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_STListarActionPerformed

    private void jSAListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSAListarActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, e);
        }
        DefaultTableModel model = (DefaultTableModel) STAula.getModel();
        int n = 0;
        while(n < model.getRowCount()){
            model.removeRow(n);
        }
        try {
            query = "SELECT b.nome as mat, a.nome as prof, a.cel, "
                    + "c.preço, c.local from pessoa as a, materia as b, " +
                    "aula as c WHERE b.nome = '" + JSAmat.getText()+ "' and b.id = c.materiaid and c.cpf_prof = a.cpf;";
            stm = con.createStatement();
            rs = stm.executeQuery(query);
            while(rs.next()){
                model.addRow(new Object[]{rs.getString("mat"),rs.getString("prof"),
                    rs.getString("cel"), rs.getString("preço"), rs.getString("local")});
        }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, e);

        }
    }//GEN-LAST:event_jSAListarActionPerformed

    private void TurmaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurmaInActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("org.postgresql.Driver");
            con = DriverManager.getConnection(URL, User, Password);
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Falha na conexão");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DB.class.getName()).log(Level.SEVERE, null, ex);
        }
        query = "INSERT INTO turma VALUES ((SELECT b.id FROM materia as a, aula as b WHERE a.id = "
                + "b.materiaid and a.nome = '"+ JSAmat.getText() +"'), " + TinCPF.getText() + ");";
        try {
            stm = con.createStatement();
            stm.executeUpdate(query);
            con.close();
            JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }//GEN-LAST:event_TurmaInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB().setVisible(true);
            }
        });
    }

    String URL = "jdbc:postgresql://localhost:15432/dbproject";
    Connection con;
    Statement stm;
    ResultSet rs;
    String User = "miguel";
    String Password = "macross";
    String query;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CACPF_Prof;
    private javax.swing.JButton CACriar;
    private javax.swing.JTextField CAPreço;
    private javax.swing.JTextField CAname_mat;
    private javax.swing.JMenuItem CClass;
    private javax.swing.JMenuItem CMat;
    private javax.swing.JTextField CPF;
    private javax.swing.JMenuItem CUser;
    private javax.swing.JTextField Cel;
    private javax.swing.JButton DADelete;
    private javax.swing.JTextField DAID;
    private javax.swing.JTextField DCPF;
    private javax.swing.JMenuItem DClass;
    private javax.swing.JButton DUDelete;
    private javax.swing.JMenuItem DUser;
    private javax.swing.JMenu Delete;
    private javax.swing.JComboBox<String> Dia;
    private javax.swing.JComboBox<String> Hora;
    private javax.swing.JMenu Insert;
    private javax.swing.JMenuBar JMenu;
    private javax.swing.JTextField JSAmat;
    private javax.swing.JTextField Local;
    private javax.swing.JButton MInsert;
    private javax.swing.JComboBox<String> Mes;
    private javax.swing.JComboBox<String> Minuto;
    private javax.swing.JTextField NMat;
    private javax.swing.JPasswordField Passwd;
    private javax.swing.JTextField SAID;
    private javax.swing.JTable SAula;
    private javax.swing.JMenuItem SClass;
    private javax.swing.JTable STAula;
    private javax.swing.JButton STListar;
    private javax.swing.JMenuItem STurma;
    private javax.swing.JMenu Select;
    private javax.swing.JComboBox<String> Sexo;
    private javax.swing.JTextField TinCPF;
    private javax.swing.JButton TurmaIn;
    private javax.swing.JButton UInserir;
    private javax.swing.JTextField UNome;
    private javax.swing.JComboBox<String> ano;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCAula;
    private javax.swing.JPanel jPCMat;
    private javax.swing.JPanel jPCUser;
    private javax.swing.JPanel jPDAula;
    private javax.swing.JPanel jPDUser;
    private javax.swing.JPanel jPSAula;
    private javax.swing.JPanel jPSTurma;
    private javax.swing.JButton jSAListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
